### PR TITLE
Freedom of speech

### PR DESCRIPTION
**Pull request by saingsocheat**
[Static Content CI](https://github.com/WorldHealthOrganization/app/actions/workflows/static-content.yaml)

### CODE REVIEW

**Comment by saingsocheat** [comment]
> [Static Content CI](https://github.com/WorldHealthOrganization/app/actions/workflows/static-content.yaml)

https://EditorConfig.org

**Comment by saingsocheat** [comment]
https://github.com/WorldHealthOrganization/app/actions/workflows/static-content.yaml/badge.svg

**Comment by saingsocheat** [comment]
[Add docs-reviewers request to the docs-content review board](https://github.com/saingsocheat/docs/actions/workflows/docs-review-collect.yml)

**Comment by megasanjay** [comment]
🤔

**Pull request closed without merging**
